name: Check linting

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  check-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install lint dependencies
        run: pip install black==22.3.0 isort==5.10.1 flake8==4.0.1

      - name: Lint the code
        run: sh shell/lint.sh
