name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: pip install wheel setuptools
    
      - name: Build package
        run: python setup.py bdist_wheel
    
      - name: Upload Python wheel
        uses: actions/upload-artifact@v4
        with:
          name: "Python wheel"
          path: ./dist/*
          if-no-files-found: error
    
      - name: Upload APK to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.CI_TOKEN }}
          file: ./dist/vsi2tif-*.whl
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
